<?php
/*
Plugin Name: M'Cheyne Reading Plan
Description: Provides a widget that lists the daily Bible readings from Robert Murray M'Cheyne's Bible reading calendar.
Version: 1.0
Author: Will Norris
Author URI: https://willnorris.com/
*/

add_action('widgets_init', 'mcheyne_widgets_init');
function mcheyne_widgets_init() {
  register_widget('Widget_MCheyne_Reading_Plan');
}

class Widget_MCheyne_Reading_Plan extends WP_Widget {
  function __construct() {
    $widget_ops = array('classname' => 'widget_mcheyne_reading_plan', 'description' => __( "Robert Murray M'Cheyne's Bible reading calendar.") );
    parent::__construct('mcheyne-reading-plan', __('Daily Reading Plan'), $widget_ops);
    $this->alt_option_name = 'widget_mcheyne_reading_plan';
  }

  function widget($args, $instance) {
    if ( ! isset( $args['widget_id'] ) ) {
      $args['widget_id'] = $this->id;
    }

    extract($args);

    $title = ( ! empty( $instance['title'] ) ) ? $instance['title'] : __( "Today's Bible Reading" );
    $title = apply_filters( 'widget_title', $title, $instance, $this->id_base );

    $calendar = mcheyne_calendar();
    $now = current_time('timestamp');
    $plan = $calendar[date('n', $now)][date('j', $now)];

    echo $before_widget; ?>
    <?php if ( $title ) echo $before_title . $title . $after_title; ?>
    <ul>
      <li><?php echo $this->bible_link($plan['family'][0]) ?></li>
      <li><?php echo $this->bible_link($plan['family'][1]) ?></li>
      <li><?php echo $this->bible_link($plan['secret'][0]) ?></li>
      <li><?php echo $this->bible_link($plan['secret'][1]) ?></li>
    </ul>

    <p class="download-link"><a href="<?php echo plugins_url('calendar.pdf', __FILE__) ?>">Bible Reading Calendar</a></p>
    <?php echo $after_widget;
  }

  function bible_link($passage) {
    $link = '<a href="http://www.biblegateway.com/passage/?version=nkjv&search=' . urlencode($passage) . '">' . $passage . '</a>';
    return apply_filters('mcheyne_bible_link', $link, $passage);
  }

  function update($new_instance, $old_instance) {
    $instance = $old_instance;
    $instance['title'] = strip_tags($new_instance['title']);
    return $instance;
  }

  function form($instance) {
    $title = isset( $instance['title'] ) ? esc_attr( $instance['title'] ) : '';
?>
    <p><label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:' ); ?></label>
    <input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo $title; ?>" />
<?php
  }

}


function mcheyne_calendar() {
  return array(
    '1' => array(
      '1' => array( 'family' => array('Genesis 1', 'Matthew 1'), 'secret' => array('Ezra 1', 'Acts 1') ),
      '2' => array( 'family' => array('Genesis 2', 'Matthew 2'), 'secret' => array('Ezra 2', 'Acts 2') ),
      '3' => array( 'family' => array('Genesis 3', 'Matthew 3'), 'secret' => array('Ezra 3', 'Acts 3') ),
      '4' => array( 'family' => array('Genesis 4', 'Matthew 4'), 'secret' => array('Ezra 4', 'Acts 4') ),
      '5' => array( 'family' => array('Genesis 5', 'Matthew 5'), 'secret' => array('Ezra 5', 'Acts 5') ),
      '6' => array( 'family' => array('Genesis 6', 'Matthew 6'), 'secret' => array('Ezra 6', 'Acts 6') ),
      '7' => array( 'family' => array('Genesis 7', 'Matthew 7'), 'secret' => array('Ezra 7', 'Acts 7') ),
      '8' => array( 'family' => array('Genesis 8', 'Matthew 8'), 'secret' => array('Ezra 8', 'Acts 8') ),
      '9' => array( 'family' => array('Genesis 9-10', 'Matthew 9'), 'secret' => array('Ezra 9', 'Acts 9') ),
      '10' => array( 'family' => array('Genesis 11', 'Matthew 10'), 'secret' => array('Ezra 10', 'Acts 10') ),
      '11' => array( 'family' => array('Genesis 12', 'Matthew 11'), 'secret' => array('Nehemiah 1', 'Acts 11') ),
      '12' => array( 'family' => array('Genesis 13', 'Matthew 12'), 'secret' => array('Nehemiah 2', 'Acts 12') ),
      '13' => array( 'family' => array('Genesis 14', 'Matthew 13'), 'secret' => array('Nehemiah 3', 'Acts 13') ),
      '14' => array( 'family' => array('Genesis 15', 'Matthew 14'), 'secret' => array('Nehemiah 4', 'Acts 14') ),
      '15' => array( 'family' => array('Genesis 16', 'Matthew 15'), 'secret' => array('Nehemiah 5', 'Acts 15') ),
      '16' => array( 'family' => array('Genesis 17', 'Matthew 16'), 'secret' => array('Nehemiah 6', 'Acts 16') ),
      '17' => array( 'family' => array('Genesis 18', 'Matthew 17'), 'secret' => array('Nehemiah 7', 'Acts 17') ),
      '18' => array( 'family' => array('Genesis 19', 'Matthew 18'), 'secret' => array('Nehemiah 8', 'Acts 18') ),
      '19' => array( 'family' => array('Genesis 20', 'Matthew 19'), 'secret' => array('Nehemiah 9', 'Acts 19') ),
      '20' => array( 'family' => array('Genesis 21', 'Matthew 20'), 'secret' => array('Nehemiah 10', 'Acts 20') ),
      '21' => array( 'family' => array('Genesis 22', 'Matthew 21'), 'secret' => array('Nehemiah 11', 'Acts 21') ),
      '22' => array( 'family' => array('Genesis 23', 'Matthew 22'), 'secret' => array('Nehemiah 12', 'Acts 22') ),
      '23' => array( 'family' => array('Genesis 24', 'Matthew 23'), 'secret' => array('Nehemiah 13', 'Acts 23') ),
      '24' => array( 'family' => array('Genesis 25', 'Matthew 24'), 'secret' => array('Esther 1', 'Acts 24') ),
      '25' => array( 'family' => array('Genesis 26', 'Matthew 25'), 'secret' => array('Esther 2', 'Acts 25') ),
      '26' => array( 'family' => array('Genesis 27', 'Matthew 26'), 'secret' => array('Esther 3', 'Acts 26') ),
      '27' => array( 'family' => array('Genesis 28', 'Matthew 27'), 'secret' => array('Esther 4', 'Acts 27') ),
      '28' => array( 'family' => array('Genesis 29', 'Matthew 28'), 'secret' => array('Esther 5', 'Acts 28') ),
      '29' => array( 'family' => array('Genesis 30', 'Mark 1'), 'secret' => array('Esther 6', 'Romans 1') ),
      '30' => array( 'family' => array('Genesis 31', 'Mark 2'), 'secret' => array('Esther 7', 'Romans 2') ),
      '31' => array( 'family' => array('Genesis 32', 'Mark 3'), 'secret' => array('Esther 8', 'Romans 3') ),
    ),
    '2' => array(
      '1' => array( 'family' => array('Genesis 33', 'Mark 4'), 'secret' => array('Esther 9-10', 'Romans 4') ),
      '2' => array( 'family' => array('Genesis 34', 'Mark 5'), 'secret' => array('Job 1', 'Romans 5') ),
      '3' => array( 'family' => array('Genesis 35-36', 'Mark 6'), 'secret' => array('Job 2', 'Romans 6') ),
      '4' => array( 'family' => array('Genesis 37', 'Mark 7'), 'secret' => array('Job 3', 'Romans 7') ),
      '5' => array( 'family' => array('Genesis 38', 'Mark 8'), 'secret' => array('Job 4', 'Romans 8') ),
      '6' => array( 'family' => array('Genesis 39', 'Mark 9'), 'secret' => array('Job 5', 'Romans 9') ),
      '7' => array( 'family' => array('Genesis 40', 'Mark 10'), 'secret' => array('Job 6', 'Romans 10') ),
      '8' => array( 'family' => array('Genesis 41', 'Mark 11'), 'secret' => array('Job 7', 'Romans 11') ),
      '9' => array( 'family' => array('Genesis 42', 'Mark 12'), 'secret' => array('Job 8', 'Romans 12') ),
      '10' => array( 'family' => array('Genesis 43', 'Mark 13'), 'secret' => array('Job 9', 'Romans 13') ),
      '11' => array( 'family' => array('Genesis 44', 'Mark 14'), 'secret' => array('Job 10', 'Romans 14') ),
      '12' => array( 'family' => array('Genesis 45', 'Mark 15'), 'secret' => array('Job 11', 'Romans 15') ),
      '13' => array( 'family' => array('Genesis 46', 'Mark 16'), 'secret' => array('Job 12', 'Romans 16') ),
      '14' => array( 'family' => array('Genesis 47', 'Luke 1:1-38'), 'secret' => array('Job 13', '1 Corinthians 1') ),
      '15' => array( 'family' => array('Genesis 48', 'Luke 1:39-80'), 'secret' => array('Job 14', '1 Corinthians 2') ),
      '16' => array( 'family' => array('Genesis 49', 'Luke 2'), 'secret' => array('Job 15', '1 Corinthians 3') ),
      '17' => array( 'family' => array('Genesis 50', 'Luke 3'), 'secret' => array('Job 16-17', '1 Corinthians 4') ),
      '18' => array( 'family' => array('Exodus 1', 'Luke 4'), 'secret' => array('Job 18', '1 Corinthians 5') ),
      '19' => array( 'family' => array('Exodus 2', 'Luke 5'), 'secret' => array('Job 19', '1 Corinthians 6') ),
      '20' => array( 'family' => array('Exodus 3', 'Luke 6'), 'secret' => array('Job 20', '1 Corinthians 7') ),
      '21' => array( 'family' => array('Exodus 4', 'Luke 7'), 'secret' => array('Job 21', '1 Corinthians 8') ),
      '22' => array( 'family' => array('Exodus 5', 'Luke 8'), 'secret' => array('Job 22', '1 Corinthians 9') ),
      '23' => array( 'family' => array('Exodus 6', 'Luke 9'), 'secret' => array('Job 23', '1 Corinthians 10') ),
      '24' => array( 'family' => array('Exodus 7', 'Luke 10'), 'secret' => array('Job 24', '1 Corinthians 11') ),
      '25' => array( 'family' => array('Exodus 8', 'Luke 11'), 'secret' => array('Job 25-26', '1 Corinthians 12') ),
      '26' => array( 'family' => array('Exodus 9', 'Luke 12'), 'secret' => array('Job 27', '1 Corinthians 13') ),
      '27' => array( 'family' => array('Exodus 10', 'Luke 13'), 'secret' => array('Job 28', '1 Corinthians 14') ),
      '28' => array( 'family' => array('Exodus 11:1-12:21', 'Luke 14'), 'secret' => array('Job 29', '1 Corinthians 15') ),
    ),
    '3' => array(
      '1' => array( 'family' => array('Exodus 12:22-51', 'Luke 15'), 'secret' => array('Job 30', '1 Corinthians 16') ),
      '2' => array( 'family' => array('Exodus 13', 'Luke 16'), 'secret' => array('Job 31', '2 Corinthians 1') ),
      '3' => array( 'family' => array('Exodus 14', 'Luke 17'), 'secret' => array('Job 32', '2 Corinthians 2') ),
      '4' => array( 'family' => array('Exodus 15', 'Luke 18'), 'secret' => array('Job 33', '2 Corinthians 3') ),
      '5' => array( 'family' => array('Exodus 16', 'Luke 19'), 'secret' => array('Job 34', '2 Corinthians 4') ),
      '6' => array( 'family' => array('Exodus 17', 'Luke 20'), 'secret' => array('Job 35', '2 Corinthians 5') ),
      '7' => array( 'family' => array('Exodus 18', 'Luke 21'), 'secret' => array('Job 36', '2 Corinthians 6') ),
      '8' => array( 'family' => array('Exodus 19', 'Luke 22'), 'secret' => array('Job 37', '2 Corinthians 7') ),
      '9' => array( 'family' => array('Exodus 20', 'Luke 23'), 'secret' => array('Job 38', '2 Corinthians 8') ),
      '10' => array( 'family' => array('Exodus 21', 'Luke 24'), 'secret' => array('Job 39', '2 Corinthians 9') ),
      '11' => array( 'family' => array('Exodus 22', 'John 1'), 'secret' => array('Job 40', '2 Corinthians 10') ),
      '12' => array( 'family' => array('Exodus 23', 'John 2'), 'secret' => array('Job 41', '2 Corinthians 11') ),
      '13' => array( 'family' => array('Exodus 24', 'John 3'), 'secret' => array('Job 42', '2 Corinthians 12') ),
      '14' => array( 'family' => array('Exodus 25', 'John 4'), 'secret' => array('Proverbs 1', '2 Corinthians 13') ),
      '15' => array( 'family' => array('Exodus 26', 'John 5'), 'secret' => array('Proverbs 2', 'Galatians 1') ),
      '16' => array( 'family' => array('Exodus 27', 'John 6'), 'secret' => array('Proverbs 3', 'Galatians 2') ),
      '17' => array( 'family' => array('Exodus 28', 'John 7'), 'secret' => array('Proverbs 4', 'Galatians 3') ),
      '18' => array( 'family' => array('Exodus 29', 'John 8'), 'secret' => array('Proverbs 5', 'Galatians 4') ),
      '19' => array( 'family' => array('Exodus 30', 'John 9'), 'secret' => array('Proverbs 6', 'Galatians 5') ),
      '20' => array( 'family' => array('Exodus 31', 'John 10'), 'secret' => array('Proverbs 7', 'Galatians 6') ),
      '21' => array( 'family' => array('Exodus 32', 'John 11'), 'secret' => array('Proverbs 8', 'Ephesians 1') ),
      '22' => array( 'family' => array('Exodus 33', 'John 12'), 'secret' => array('Proverbs 9', 'Ephesians 2') ),
      '23' => array( 'family' => array('Exodus 34', 'John 13'), 'secret' => array('Proverbs 10', 'Ephesians 3') ),
      '24' => array( 'family' => array('Exodus 35', 'John 14'), 'secret' => array('Proverbs 11', 'Ephesians 4') ),
      '25' => array( 'family' => array('Exodus 36', 'John 15'), 'secret' => array('Proverbs 12', 'Ephesians 5') ),
      '26' => array( 'family' => array('Exodus 37', 'John 16'), 'secret' => array('Proverbs 13', 'Ephesians 6') ),
      '27' => array( 'family' => array('Exodus 38', 'John 17'), 'secret' => array('Proverbs 14', 'Philippians 1') ),
      '28' => array( 'family' => array('Exodus 39', 'John 18'), 'secret' => array('Proverbs 15', 'Philippians 2') ),
      '29' => array( 'family' => array('Exodus 40', 'John 19'), 'secret' => array('Proverbs 16', 'Philippians 3') ),
      '30' => array( 'family' => array('Leviticus 1', 'John 20'), 'secret' => array('Proverbs 17', 'Philippians 4') ),
      '31' => array( 'family' => array('Leviticus 2-3', 'John 21'), 'secret' => array('Proverbs 18', 'Colossians 1') ),
    ),
    '4' => array(
      '1' => array( 'family' => array('Leviticus 4', 'Psalms 1-2'), 'secret' => array('Proverbs 19', 'Colossians 2') ),
      '2' => array( 'family' => array('Leviticus 5', 'Psalms 3-4'), 'secret' => array('Proverbs 20', 'Colossians 3') ),
      '3' => array( 'family' => array('Leviticus 6', 'Psalms 5-6'), 'secret' => array('Proverbs 21', 'Colossians 4') ),
      '4' => array( 'family' => array('Leviticus 7', 'Psalms 7-8'), 'secret' => array('Proverbs 22', '1 Thessalonians 1') ),
      '5' => array( 'family' => array('Leviticus 8', 'Psalms 9'), 'secret' => array('Proverbs 23', '1 Thessalonians 2') ),
      '6' => array( 'family' => array('Leviticus 9', 'Psalms 10'), 'secret' => array('Proverbs 24', '1 Thessalonians 3') ),
      '7' => array( 'family' => array('Leviticus 10', 'Psalms 11-12'), 'secret' => array('Proverbs 25', '1 Thessalonians 4') ),
      '8' => array( 'family' => array('Leviticus 11-12', 'Psalms 13-14'), 'secret' => array('Proverbs 26', '1 Thessalonians 5') ),
      '9' => array( 'family' => array('Leviticus 13', 'Psalms 15-16'), 'secret' => array('Proverbs 27', '2 Thessalonians 1') ),
      '10' => array( 'family' => array('Leviticus 14', 'Psalms 17'), 'secret' => array('Proverbs 28', '2 Thessalonians 2') ),
      '11' => array( 'family' => array('Leviticus 15', 'Psalms 18'), 'secret' => array('Proverbs 29', '2 Thessalonians 3') ),
      '12' => array( 'family' => array('Leviticus 16', 'Psalms 19'), 'secret' => array('Proverbs 30', '1 Timothy 1') ),
      '13' => array( 'family' => array('Leviticus 17', 'Psalms 20-21'), 'secret' => array('Proverbs 31', '1 Timothy 2') ),
      '14' => array( 'family' => array('Leviticus 18', 'Psalms 22'), 'secret' => array('Ecclesiastes 1', '1 Timothy 3') ),
      '15' => array( 'family' => array('Leviticus 19', 'Psalms 23-24'), 'secret' => array('Ecclesiastes 2', '1 Timothy 4') ),
      '16' => array( 'family' => array('Leviticus 20', 'Psalms 25'), 'secret' => array('Ecclesiastes 3', '1 Timothy 5') ),
      '17' => array( 'family' => array('Leviticus 21', 'Psalms 26-27'), 'secret' => array('Ecclesiastes 4', '1 Timothy 6') ),
      '18' => array( 'family' => array('Leviticus 22', 'Psalms 28-29'), 'secret' => array('Ecclesiastes 5', '2 Timothy 1') ),
      '19' => array( 'family' => array('Leviticus 23', 'Psalms 30'), 'secret' => array('Ecclesiastes 6', '2 Timothy 2') ),
      '20' => array( 'family' => array('Leviticus 24', 'Psalms 31'), 'secret' => array('Ecclesiastes 7', '2 Timothy 3') ),
      '21' => array( 'family' => array('Leviticus 25', 'Psalms 32'), 'secret' => array('Ecclesiastes 8', '2 Timothy 4') ),
      '22' => array( 'family' => array('Leviticus 26', 'Psalms 33'), 'secret' => array('Ecclesiastes 9', 'Titus 1') ),
      '23' => array( 'family' => array('Leviticus 27', 'Psalms 34'), 'secret' => array('Ecclesiastes 10', 'Titus 2') ),
      '24' => array( 'family' => array('Numbers 1', 'Psalms 35'), 'secret' => array('Ecclesiastes 11', 'Titus 3') ),
      '25' => array( 'family' => array('Numbers 2', 'Psalms 36'), 'secret' => array('Ecclesiastes 12', 'Philemon 1') ),
      '26' => array( 'family' => array('Numbers 3', 'Psalms 37'), 'secret' => array('Song of Songs 1', 'Hebrews 1') ),
      '27' => array( 'family' => array('Numbers 4', 'Psalms 38'), 'secret' => array('Song of Songs 2', 'Hebrews 2') ),
      '28' => array( 'family' => array('Numbers 5', 'Psalms 39'), 'secret' => array('Song of Songs 3', 'Hebrews 3') ),
      '29' => array( 'family' => array('Numbers 6', 'Psalms 40-41'), 'secret' => array('Song of Songs 4', 'Hebrews 4') ),
      '30' => array( 'family' => array('Numbers 7', 'Psalms 42-43'), 'secret' => array('Song of Songs 5', 'Hebrews 5') ),
    ),
    '5' => array(
      '1' => array( 'family' => array('Numbers 8', 'Psalms 44'), 'secret' => array('Song of Songs 6', 'Hebrews 6') ),
      '2' => array( 'family' => array('Numbers 9', 'Psalms 45'), 'secret' => array('Song of Songs 7', 'Hebrews 7') ),
      '3' => array( 'family' => array('Numbers 10', 'Psalms 46-47'), 'secret' => array('Song of Songs 8', 'Hebrews 8') ),
      '4' => array( 'family' => array('Numbers 11', 'Psalms 48'), 'secret' => array('Isaiah 1', 'Hebrews 9') ),
      '5' => array( 'family' => array('Numbers 12-13', 'Psalms 49'), 'secret' => array('Isaiah 2', 'Hebrews 10') ),
      '6' => array( 'family' => array('Numbers 14', 'Psalms 50'), 'secret' => array('Isaiah 3-4', 'Hebrews 11') ),
      '7' => array( 'family' => array('Numbers 15', 'Psalms 51'), 'secret' => array('Isaiah 5', 'Hebrews 12') ),
      '8' => array( 'family' => array('Numbers 16', 'Psalms 52-54'), 'secret' => array('Isaiah 6', 'Hebrews 13') ),
      '9' => array( 'family' => array('Numbers 17-18', 'Psalms 55'), 'secret' => array('Isaiah 7', 'James 1') ),
      '10' => array( 'family' => array('Numbers 19', 'Psalms 56-57'), 'secret' => array('Isaiah 8:1-9:7', 'James 2') ),
      '11' => array( 'family' => array('Numbers 20', 'Psalms 58-59'), 'secret' => array('Isaiah 9:8-10:4', 'James 3') ),
      '12' => array( 'family' => array('Numbers 21', 'Psalms 60-61'), 'secret' => array('Isaiah 10:5-34', 'James 4') ),
      '13' => array( 'family' => array('Numbers 22', 'Psalms 62-63'), 'secret' => array('Isaiah 11-12', 'James 5') ),
      '14' => array( 'family' => array('Numbers 23', 'Psalms 64-65'), 'secret' => array('Isaiah 13', '1 Peter 1') ),
      '15' => array( 'family' => array('Numbers 24', 'Psalms 66-67'), 'secret' => array('Isaiah 14', '1 Peter 2') ),
      '16' => array( 'family' => array('Numbers 25', 'Psalms 68'), 'secret' => array('Isaiah 15', '1 Peter 3') ),
      '17' => array( 'family' => array('Numbers 26', 'Psalms 69'), 'secret' => array('Isaiah 16', '1 Peter 4') ),
      '18' => array( 'family' => array('Numbers 27', 'Psalms 70-71'), 'secret' => array('Isaiah 17-18', '1 Peter 5') ),
      '19' => array( 'family' => array('Numbers 28', 'Psalms 72'), 'secret' => array('Isaiah 19-20', '2 Peter 1') ),
      '20' => array( 'family' => array('Numbers 29', 'Psalms 73'), 'secret' => array('Isaiah 21', '2 Peter 2') ),
      '21' => array( 'family' => array('Numbers 30', 'Psalms 74'), 'secret' => array('Isaiah 22', '2 Peter 3') ),
      '22' => array( 'family' => array('Numbers 31', 'Psalms 75-76'), 'secret' => array('Isaiah 23', '1 John 1') ),
      '23' => array( 'family' => array('Numbers 32', 'Psalms 77'), 'secret' => array('Isaiah 24', '1 John 2') ),
      '24' => array( 'family' => array('Numbers 33', 'Psalms 78:1-37'), 'secret' => array('Isaiah 25', '1 John 3') ),
      '25' => array( 'family' => array('Numbers 34', 'Psalms 78:38-72'), 'secret' => array('Isaiah 26', '1 John 4') ),
      '26' => array( 'family' => array('Numbers 35', 'Psalms 79'), 'secret' => array('Isaiah 27', '1 John 5') ),
      '27' => array( 'family' => array('Numbers 36', 'Psalms 80'), 'secret' => array('Isaiah 28', '2 John 1') ),
      '28' => array( 'family' => array('Deuteronomy 1', 'Psalms 81-82'), 'secret' => array('Isaiah 29', '3 John 1') ),
      '29' => array( 'family' => array('Deuteronomy 2', 'Psalms 83-84'), 'secret' => array('Isaiah 30', 'Jude 1') ),
      '30' => array( 'family' => array('Deuteronomy 3', 'Psalms 85'), 'secret' => array('Isaiah 31', 'Revelation 1') ),
      '31' => array( 'family' => array('Deuteronomy 4', 'Psalms 86-87'), 'secret' => array('Isaiah 32', 'Revelation 2') ),
    ),
    '6' => array(
      '1' => array( 'family' => array('Deuteronomy 5', 'Psalms 88'), 'secret' => array('Isaiah 33', 'Revelation 3') ),
      '2' => array( 'family' => array('Deuteronomy 6', 'Psalms 89'), 'secret' => array('Isaiah 34', 'Revelation 4') ),
      '3' => array( 'family' => array('Deuteronomy 7', 'Psalms 90'), 'secret' => array('Isaiah 35', 'Revelation 5') ),
      '4' => array( 'family' => array('Deuteronomy 8', 'Psalms 91'), 'secret' => array('Isaiah 36', 'Revelation 6') ),
      '5' => array( 'family' => array('Deuteronomy 9', 'Psalms 92-93'), 'secret' => array('Isaiah 37', 'Revelation 7') ),
      '6' => array( 'family' => array('Deuteronomy 10', 'Psalms 94'), 'secret' => array('Isaiah 38', 'Revelation 8') ),
      '7' => array( 'family' => array('Deuteronomy 11', 'Psalms 95-96'), 'secret' => array('Isaiah 39', 'Revelation 9') ),
      '8' => array( 'family' => array('Deuteronomy 12', 'Psalms 97-98'), 'secret' => array('Isaiah 40', 'Revelation 10') ),
      '9' => array( 'family' => array('Deuteronomy 13-14', 'Psalms 99-101'), 'secret' => array('Isaiah 41', 'Revelation 11') ),
      '10' => array( 'family' => array('Deuteronomy 15', 'Psalms 102'), 'secret' => array('Isaiah 42', 'Revelation 12') ),
      '11' => array( 'family' => array('Deuteronomy 16', 'Psalms 103'), 'secret' => array('Isaiah 43', 'Revelation 13') ),
      '12' => array( 'family' => array('Deuteronomy 17', 'Psalms 104'), 'secret' => array('Isaiah 44', 'Revelation 14') ),
      '13' => array( 'family' => array('Deuteronomy 18', 'Psalms 105'), 'secret' => array('Isaiah 45', 'Revelation 15') ),
      '14' => array( 'family' => array('Deuteronomy 19', 'Psalms 106'), 'secret' => array('Isaiah 46', 'Revelation 16') ),
      '15' => array( 'family' => array('Deuteronomy 20', 'Psalms 107'), 'secret' => array('Isaiah 47', 'Revelation 17') ),
      '16' => array( 'family' => array('Deuteronomy 21', 'Psalms 108-109'), 'secret' => array('Isaiah 48', 'Revelation 18') ),
      '17' => array( 'family' => array('Deuteronomy 22', 'Psalms 110-111'), 'secret' => array('Isaiah 49', 'Revelation 19') ),
      '18' => array( 'family' => array('Deuteronomy 23', 'Psalms 112-113'), 'secret' => array('Isaiah 50', 'Revelation 20') ),
      '19' => array( 'family' => array('Deuteronomy 24', 'Psalms 114-115'), 'secret' => array('Isaiah 51', 'Revelation 21') ),
      '20' => array( 'family' => array('Deuteronomy 25', 'Psalms 116'), 'secret' => array('Isaiah 52', 'Revelation 22') ),
      '21' => array( 'family' => array('Deuteronomy 26', 'Psalms 117-118'), 'secret' => array('Isaiah 53', 'Matthew 1') ),
      '22' => array( 'family' => array('Deuteronomy 27:1-28:19', 'Psalms 119:1-24'), 'secret' => array('Isaiah 54', 'Matthew 2') ),
      '23' => array( 'family' => array('Deuteronomy 28:20-68', 'Psalms 119:25-48'), 'secret' => array('Isaiah 55', 'Matthew 3') ),
      '24' => array( 'family' => array('Deuteronomy 29', 'Psalms 119:49-72'), 'secret' => array('Isaiah 56', 'Matthew 4') ),
      '25' => array( 'family' => array('Deuteronomy 30', 'Psalms 119:73-96'), 'secret' => array('Isaiah 57', 'Matthew 5') ),
      '26' => array( 'family' => array('Deuteronomy 31', 'Psalms 119:97-120'), 'secret' => array('Isaiah 58', 'Matthew 6') ),
      '27' => array( 'family' => array('Deuteronomy 32', 'Psalms 119:121-144'), 'secret' => array('Isaiah 59', 'Matthew 7') ),
      '28' => array( 'family' => array('Deuteronomy 33-34', 'Psalms 119:145-176'), 'secret' => array('Isaiah 60', 'Matthew 8') ),
      '29' => array( 'family' => array('Joshua 1', 'Psalms 120-122'), 'secret' => array('Isaiah 61', 'Matthew 9') ),
      '30' => array( 'family' => array('Joshua 2', 'Psalms 123-125'), 'secret' => array('Isaiah 62', 'Matthew 10') ),
    ),
    '7' => array(
      '1' => array( 'family' => array('Joshua 3', 'Psalms 126-128'), 'secret' => array('Isaiah 63', 'Matthew 11') ),
      '2' => array( 'family' => array('Joshua 4', 'Psalms 129-131'), 'secret' => array('Isaiah 64', 'Matthew 12') ),
      '3' => array( 'family' => array('Joshua 5:1-6:5', 'Psalms 132-134'), 'secret' => array('Isaiah 65', 'Matthew 13') ),
      '4' => array( 'family' => array('Joshua 6:6-27', 'Psalms 135-136'), 'secret' => array('Isaiah 66', 'Matthew 14') ),
      '5' => array( 'family' => array('Joshua 7', 'Psalms 137-138'), 'secret' => array('Jeremiah 1', 'Matthew 15') ),
      '6' => array( 'family' => array('Joshua 8', 'Psalms 139'), 'secret' => array('Jeremiah 2', 'Matthew 16') ),
      '7' => array( 'family' => array('Joshua 9', 'Psalms 140-141'), 'secret' => array('Jeremiah 3', 'Matthew 17') ),
      '8' => array( 'family' => array('Joshua 10', 'Psalms 142-143'), 'secret' => array('Jeremiah 4', 'Matthew 18') ),
      '9' => array( 'family' => array('Joshua 11', 'Psalms 144'), 'secret' => array('Jeremiah 5', 'Matthew 19') ),
      '10' => array( 'family' => array('Joshua 12-13', 'Psalms 145'), 'secret' => array('Jeremiah 6', 'Matthew 20') ),
      '11' => array( 'family' => array('Joshua 14-15', 'Psalms 146-147'), 'secret' => array('Jeremiah 7', 'Matthew 21') ),
      '12' => array( 'family' => array('Joshua 16-17', 'Psalms 148'), 'secret' => array('Jeremiah 8', 'Matthew 22') ),
      '13' => array( 'family' => array('Joshua 18-19', 'Psalms 149-150'), 'secret' => array('Jeremiah 9', 'Matthew 23') ),
      '14' => array( 'family' => array('Joshua 20-21', 'Acts 1'), 'secret' => array('Jeremiah 10', 'Matthew 24') ),
      '15' => array( 'family' => array('Joshua 22', 'Acts 2'), 'secret' => array('Jeremiah 11', 'Matthew 25') ),
      '16' => array( 'family' => array('Joshua 23', 'Acts 3'), 'secret' => array('Jeremiah 12', 'Matthew 26') ),
      '17' => array( 'family' => array('Joshua 24', 'Acts 4'), 'secret' => array('Jeremiah 13', 'Matthew 27') ),
      '18' => array( 'family' => array('Judges 1', 'Acts 5'), 'secret' => array('Jeremiah 14', 'Matthew 28') ),
      '19' => array( 'family' => array('Judges 2', 'Acts 6'), 'secret' => array('Jeremiah 15', 'Mark 1') ),
      '20' => array( 'family' => array('Judges 3', 'Acts 7'), 'secret' => array('Jeremiah 16', 'Mark 2') ),
      '21' => array( 'family' => array('Judges 4', 'Acts 8'), 'secret' => array('Jeremiah 17', 'Mark 3') ),
      '22' => array( 'family' => array('Judges 5', 'Acts 9'), 'secret' => array('Jeremiah 18', 'Mark 4') ),
      '23' => array( 'family' => array('Judges 6', 'Acts 10'), 'secret' => array('Jeremiah 19', 'Mark 5') ),
      '24' => array( 'family' => array('Judges 7', 'Acts 11'), 'secret' => array('Jeremiah 20', 'Mark 6') ),
      '25' => array( 'family' => array('Judges 8', 'Acts 12'), 'secret' => array('Jeremiah 21', 'Mark 7') ),
      '26' => array( 'family' => array('Judges 9', 'Acts 13'), 'secret' => array('Jeremiah 22', 'Mark 8') ),
      '27' => array( 'family' => array('Judges 10:1-11:11', 'Acts 14'), 'secret' => array('Jeremiah 23', 'Mark 9') ),
      '28' => array( 'family' => array('Judges 11:12-40', 'Acts 15'), 'secret' => array('Jeremiah 24', 'Mark 10') ),
      '29' => array( 'family' => array('Judges 12', 'Acts 16'), 'secret' => array('Jeremiah 25', 'Mark 11') ),
      '30' => array( 'family' => array('Judges 13', 'Acts 17'), 'secret' => array('Jeremiah 26', 'Mark 12') ),
      '31' => array( 'family' => array('Judges 14', 'Acts 18'), 'secret' => array('Jeremiah 27', 'Mark 13') ),
    ),
    '8' => array(
      '1' => array( 'family' => array('Judges 15', 'Acts 19'), 'secret' => array('Jeremiah 28', 'Mark 14') ),
      '2' => array( 'family' => array('Judges 16', 'Acts 20'), 'secret' => array('Jeremiah 29', 'Mark 15') ),
      '3' => array( 'family' => array('Judges 17', 'Acts 21'), 'secret' => array('Jeremiah 30-31', 'Mark 16') ),
      '4' => array( 'family' => array('Judges 18', 'Acts 22'), 'secret' => array('Jeremiah 32', 'Psalms 1-2') ),
      '5' => array( 'family' => array('Judges 19', 'Acts 23'), 'secret' => array('Jeremiah 33', 'Psalms 3-4') ),
      '6' => array( 'family' => array('Judges 20', 'Acts 24'), 'secret' => array('Jeremiah 34', 'Psalms 5-6') ),
      '7' => array( 'family' => array('Judges 21', 'Acts 25'), 'secret' => array('Jeremiah 35', 'Psalms 7-8') ),
      '8' => array( 'family' => array('Ruth 1', 'Acts 26'), 'secret' => array('Jeremiah 36,45', 'Psalms 9') ),
      '9' => array( 'family' => array('Ruth 2', 'Acts 27'), 'secret' => array('Jeremiah 37', 'Psalms 10') ),
      '10' => array( 'family' => array('Ruth 3-4', 'Acts 28'), 'secret' => array('Jeremiah 38', 'Psalms 11-12') ),
      '11' => array( 'family' => array('1 Samuel 1', 'Romans 1'), 'secret' => array('Jeremiah 39', 'Psalms 13-14') ),
      '12' => array( 'family' => array('1 Samuel 2', 'Romans 2'), 'secret' => array('Jeremiah 40', 'Psalms 15-16') ),
      '13' => array( 'family' => array('1 Samuel 3', 'Romans 3'), 'secret' => array('Jeremiah 41', 'Psalms 17') ),
      '14' => array( 'family' => array('1 Samuel 4', 'Romans 4'), 'secret' => array('Jeremiah 42', 'Psalms 18') ),
      '15' => array( 'family' => array('1 Samuel 5-6', 'Romans 5'), 'secret' => array('Jeremiah 43', 'Psalms 19') ),
      '16' => array( 'family' => array('1 Samuel 7-8', 'Romans 6'), 'secret' => array('Jeremiah 44', 'Psalms 20-21') ),
      '17' => array( 'family' => array('1 Samuel 9', 'Romans 7'), 'secret' => array('Jeremiah 46', 'Psalms 22') ),
      '18' => array( 'family' => array('1 Samuel 10', 'Romans 8'), 'secret' => array('Jeremiah 47', 'Psalms 23-24') ),
      '19' => array( 'family' => array('1 Samuel 11', 'Romans 9'), 'secret' => array('Jeremiah 48', 'Psalms 25') ),
      '20' => array( 'family' => array('1 Samuel 12', 'Romans 10'), 'secret' => array('Jeremiah 49', 'Psalms 26-27') ),
      '21' => array( 'family' => array('1 Samuel 13', 'Romans 11'), 'secret' => array('Jeremiah 50', 'Psalms 28-29') ),
      '22' => array( 'family' => array('1 Samuel 14', 'Romans 12'), 'secret' => array('Jeremiah 51', 'Psalms 30') ),
      '23' => array( 'family' => array('1 Samuel 15', 'Romans 13'), 'secret' => array('Jeremiah 52', 'Psalms 31') ),
      '24' => array( 'family' => array('1 Samuel 16', 'Romans 14'), 'secret' => array('Lamentations 1', 'Psalms 32') ),
      '25' => array( 'family' => array('1 Samuel 17', 'Romans 15'), 'secret' => array('Lamentations 2', 'Psalms 33') ),
      '26' => array( 'family' => array('1 Samuel 18', 'Romans 16'), 'secret' => array('Lamentations 3', 'Psalms 34') ),
      '27' => array( 'family' => array('1 Samuel 19', '1 Corinthians 1'), 'secret' => array('Lamentations 4', 'Psalms 35') ),
      '28' => array( 'family' => array('1 Samuel 20', '1 Corinthians 2'), 'secret' => array('Lamentations 5', 'Psalms 36') ),
      '29' => array( 'family' => array('1 Samuel 21-22', '1 Corinthians 3'), 'secret' => array('Ezekiel 1', 'Psalms 37') ),
      '30' => array( 'family' => array('1 Samuel 23', '1 Corinthians 4'), 'secret' => array('Ezekiel 2', 'Psalms 38') ),
      '31' => array( 'family' => array('1 Samuel 24', '1 Corinthians 5'), 'secret' => array('Ezekiel 3', 'Psalms 39') ),
    ),
    '9' => array(
      '1' => array( 'family' => array('1 Samuel 25', '1 Corinthians 6'), 'secret' => array('Ezekiel 4', 'Psalms 40-41') ),
      '2' => array( 'family' => array('1 Samuel 26', '1 Corinthians 7'), 'secret' => array('Ezekiel 5', 'Psalms 42-43') ),
      '3' => array( 'family' => array('1 Samuel 27', '1 Corinthians 8'), 'secret' => array('Ezekiel 6', 'Psalms 44') ),
      '4' => array( 'family' => array('1 Samuel 28', '1 Corinthians 9'), 'secret' => array('Ezekiel 7', 'Psalms 45') ),
      '5' => array( 'family' => array('1 Samuel 29-30', '1 Corinthians 10'), 'secret' => array('Ezekiel 8', 'Psalms 46-47') ),
      '6' => array( 'family' => array('1 Samuel 31', '1 Corinthians 11'), 'secret' => array('Ezekiel 9', 'Psalms 48') ),
      '7' => array( 'family' => array('2 Samuel 1', '1 Corinthians 12'), 'secret' => array('Ezekiel 10', 'Psalms 49') ),
      '8' => array( 'family' => array('2 Samuel 2', '1 Corinthians 13'), 'secret' => array('Ezekiel 11', 'Psalms 50') ),
      '9' => array( 'family' => array('2 Samuel 3', '1 Corinthians 14'), 'secret' => array('Ezekiel 12', 'Psalms 51') ),
      '10' => array( 'family' => array('2 Samuel 4-5', '1 Corinthians 15'), 'secret' => array('Ezekiel 13', 'Psalms 52-54') ),
      '11' => array( 'family' => array('2 Samuel 6', '1 Corinthians 16'), 'secret' => array('Ezekiel 14', 'Psalms 55') ),
      '12' => array( 'family' => array('2 Samuel 7', '2 Corinthians 1'), 'secret' => array('Ezekiel 15', 'Psalms 56-57') ),
      '13' => array( 'family' => array('2 Samuel 8-9', '2 Corinthians 2'), 'secret' => array('Ezekiel 16', 'Psalms 58-59') ),
      '14' => array( 'family' => array('2 Samuel 10', '2 Corinthians 3'), 'secret' => array('Ezekiel 17', 'Psalms 60-61') ),
      '15' => array( 'family' => array('2 Samuel 11', '2 Corinthians 4'), 'secret' => array('Ezekiel 18', 'Psalms 62-63') ),
      '16' => array( 'family' => array('2 Samuel 12', '2 Corinthians 5'), 'secret' => array('Ezekiel 19', 'Psalms 64-65') ),
      '17' => array( 'family' => array('2 Samuel 13', '2 Corinthians 6'), 'secret' => array('Ezekiel 20', 'Psalms 66-67') ),
      '18' => array( 'family' => array('2 Samuel 14', '2 Corinthians 7'), 'secret' => array('Ezekiel 21', 'Psalms 68') ),
      '19' => array( 'family' => array('2 Samuel 15', '2 Corinthians 8'), 'secret' => array('Ezekiel 22', 'Psalms 69') ),
      '20' => array( 'family' => array('2 Samuel 16', '2 Corinthians 9'), 'secret' => array('Ezekiel 23', 'Psalms 70-71') ),
      '21' => array( 'family' => array('2 Samuel 17', '2 Corinthians 10'), 'secret' => array('Ezekiel 24', 'Psalms 72') ),
      '22' => array( 'family' => array('2 Samuel 18', '2 Corinthians 11'), 'secret' => array('Ezekiel 25', 'Psalms 73') ),
      '23' => array( 'family' => array('2 Samuel 19', '2 Corinthians 12'), 'secret' => array('Ezekiel 26', 'Psalms 74') ),
      '24' => array( 'family' => array('2 Samuel 20', '2 Corinthians 13'), 'secret' => array('Ezekiel 27', 'Psalms 75-76') ),
      '25' => array( 'family' => array('2 Samuel 21', 'Galatians 1'), 'secret' => array('Ezekiel 28', 'Psalms 77') ),
      '26' => array( 'family' => array('2 Samuel 22', 'Galatians 2'), 'secret' => array('Ezekiel 29', 'Psalms 78:1-37') ),
      '27' => array( 'family' => array('2 Samuel 23', 'Galatians 3'), 'secret' => array('Ezekiel 30', 'Psalms 78:38-72') ),
      '28' => array( 'family' => array('2 Samuel 24', 'Galatians 4'), 'secret' => array('Ezekiel 31', 'Psalms 79') ),
      '29' => array( 'family' => array('1 Kings 1', 'Galatians 5'), 'secret' => array('Ezekiel 32', 'Psalms 80') ),
      '30' => array( 'family' => array('1 Kings 2', 'Galatians 6'), 'secret' => array('Ezekiel 33', 'Psalms 81-82') ),
    ),
    '10' => array(
      '1' => array( 'family' => array('1 Kings 3', 'Ephesians 1'), 'secret' => array('Ezekiel 34', 'Psalms 83-84') ),
      '2' => array( 'family' => array('1 Kings 4-5', 'Ephesians 2'), 'secret' => array('Ezekiel 35', 'Psalms 85') ),
      '3' => array( 'family' => array('1 Kings 6', 'Ephesians 3'), 'secret' => array('Ezekiel 36', 'Psalms 86') ),
      '4' => array( 'family' => array('1 Kings 7', 'Ephesians 4'), 'secret' => array('Ezekiel 37', 'Psalms 87-88') ),
      '5' => array( 'family' => array('1 Kings 8', 'Ephesians 5'), 'secret' => array('Ezekiel 38', 'Psalms 89') ),
      '6' => array( 'family' => array('1 Kings 9', 'Ephesians 6'), 'secret' => array('Ezekiel 39', 'Psalms 90') ),
      '7' => array( 'family' => array('1 Kings 10', 'Philippians 1'), 'secret' => array('Ezekiel 40', 'Psalms 91') ),
      '8' => array( 'family' => array('1 Kings 11', 'Philippians 2'), 'secret' => array('Ezekiel 41', 'Psalms 92-93') ),
      '9' => array( 'family' => array('1 Kings 12', 'Philippians 3'), 'secret' => array('Ezekiel 42', 'Psalms 94') ),
      '10' => array( 'family' => array('1 Kings 13', 'Philippians 4'), 'secret' => array('Ezekiel 43', 'Psalms 95-96') ),
      '11' => array( 'family' => array('1 Kings 14', 'Colossians 1'), 'secret' => array('Ezekiel 44', 'Psalms 97-98') ),
      '12' => array( 'family' => array('1 Kings 15', 'Colossians 2'), 'secret' => array('Ezekiel 45', 'Psalms 99-101') ),
      '13' => array( 'family' => array('1 Kings 16', 'Colossians 3'), 'secret' => array('Ezekiel 46', 'Psalms 102') ),
      '14' => array( 'family' => array('1 Kings 17', 'Colossians 4'), 'secret' => array('Ezekiel 47', 'Psalms 103') ),
      '15' => array( 'family' => array('1 Kings 18', '1 Thessalonians 1'), 'secret' => array('Ezekiel 48', 'Psalms 104') ),
      '16' => array( 'family' => array('1 Kings 19', '1 Thessalonians 2'), 'secret' => array('Daniel 1', 'Psalms 105') ),
      '17' => array( 'family' => array('1 Kings 20', '1 Thessalonians 3'), 'secret' => array('Daniel 2', 'Psalms 106') ),
      '18' => array( 'family' => array('1 Kings 21', '1 Thessalonians 4'), 'secret' => array('Daniel 3', 'Psalms 107') ),
      '19' => array( 'family' => array('1 Kings 22', '1 Thessalonians 5'), 'secret' => array('Daniel 4', 'Psalms 108-109') ),
      '20' => array( 'family' => array('2 Kings 1', '2 Thessalonians 1'), 'secret' => array('Daniel 5', 'Psalms 110-111') ),
      '21' => array( 'family' => array('2 Kings 2', '2 Thessalonians 2'), 'secret' => array('Daniel 6', 'Psalms 112-113') ),
      '22' => array( 'family' => array('2 Kings 3', '2 Thessalonians 3'), 'secret' => array('Daniel 7', 'Psalms 114-115') ),
      '23' => array( 'family' => array('2 Kings 4', '1 Timothy 1'), 'secret' => array('Daniel 8', 'Psalms 116') ),
      '24' => array( 'family' => array('2 Kings 5', '1 Timothy 2'), 'secret' => array('Daniel 9', 'Psalms 117-118') ),
      '25' => array( 'family' => array('2 Kings 6', '1 Timothy 3'), 'secret' => array('Daniel 10', 'Psalms 119:1-24') ),
      '26' => array( 'family' => array('2 Kings 7', '1 Timothy 4'), 'secret' => array('Daniel 11', 'Psalms 119:25-48') ),
      '27' => array( 'family' => array('2 Kings 8', '1 Timothy 5'), 'secret' => array('Daniel 12', 'Psalms 119:49-72') ),
      '28' => array( 'family' => array('2 Kings 9', '1 Timothy 6'), 'secret' => array('Hosea 1', 'Psalms 119:73-96') ),
      '29' => array( 'family' => array('2 Kings 10', '2 Timothy 1'), 'secret' => array('Hosea 2', 'Psalms 119:97-120') ),
      '30' => array( 'family' => array('2 Kings 11-12', '2 Timothy 2'), 'secret' => array('Hosea 3-4', 'Psalms 119:121-144') ),
      '31' => array( 'family' => array('2 Kings 13', '2 Timothy 3'), 'secret' => array('Hosea 5-6', 'Psalms 119:145-176') ),
    ),
    '11' => array(
      '1' => array( 'family' => array('2 Kings 14', '2 Timothy 4'), 'secret' => array('Hosea 7', 'Psalms 120-122') ),
      '2' => array( 'family' => array('2 Kings 15', 'Titus 1'), 'secret' => array('Hosea 8', 'Psalms 123-125') ),
      '3' => array( 'family' => array('2 Kings 16', 'Titus 2'), 'secret' => array('Hosea 9', 'Psalms 126-128') ),
      '4' => array( 'family' => array('2 Kings 17', 'Titus 3'), 'secret' => array('Hosea 10', 'Psalms 129-131') ),
      '5' => array( 'family' => array('2 Kings 18', 'Philemon 1'), 'secret' => array('Hosea 11', 'Psalms 132-134') ),
      '6' => array( 'family' => array('2 Kings 19', 'Hebrews 1'), 'secret' => array('Hosea 12', 'Psalms 135-136') ),
      '7' => array( 'family' => array('2 Kings 20', 'Hebrews 2'), 'secret' => array('Hosea 13', 'Psalms 137-138') ),
      '8' => array( 'family' => array('2 Kings 21', 'Hebrews 3'), 'secret' => array('Hosea 14', 'Psalms 139') ),
      '9' => array( 'family' => array('2 Kings 22', 'Hebrews 4'), 'secret' => array('Joel 1', 'Psalms 140-141') ),
      '10' => array( 'family' => array('2 Kings 23', 'Hebrews 5'), 'secret' => array('Joel 2', 'Psalms 142') ),
      '11' => array( 'family' => array('2 Kings 24', 'Hebrews 6'), 'secret' => array('Joel 3', 'Psalms 143') ),
      '12' => array( 'family' => array('2 Kings 25', 'Hebrews 7'), 'secret' => array('Amos 1', 'Psalms 144') ),
      '13' => array( 'family' => array('1 Chronicles 1-2', 'Hebrews 8'), 'secret' => array('Amos 2', 'Psalms 145') ),
      '14' => array( 'family' => array('1 Chronicles 3-4', 'Hebrews 9'), 'secret' => array('Amos 3', 'Psalms 146-147') ),
      '15' => array( 'family' => array('1 Chronicles 5-6', 'Hebrews 10'), 'secret' => array('Amos 4', 'Psalms 148-150') ),
      '16' => array( 'family' => array('1 Chronicles 7-8', 'Hebrews 11'), 'secret' => array('Amos 5', 'Luke 1:1-38') ),
      '17' => array( 'family' => array('1 Chronicles 9-10', 'Hebrews 12'), 'secret' => array('Amos 6', 'Luke 1:39-80') ),
      '18' => array( 'family' => array('1 Chronicles 11-12', 'Hebrews 13'), 'secret' => array('Amos 7', 'Luke 2') ),
      '19' => array( 'family' => array('1 Chronicles 13-14', 'James 1'), 'secret' => array('Amos 8', 'Luke 3') ),
      '20' => array( 'family' => array('1 Chronicles 15', 'James 2'), 'secret' => array('Amos 9', 'Luke 4') ),
      '21' => array( 'family' => array('1 Chronicles 16', 'James 3'), 'secret' => array('Obadiah 1', 'Luke 5') ),
      '22' => array( 'family' => array('1 Chronicles 17', 'James 4'), 'secret' => array('Jonah 1', 'Luke 6') ),
      '23' => array( 'family' => array('1 Chronicles 18', 'James 5'), 'secret' => array('Jonah 2', 'Luke 7') ),
      '24' => array( 'family' => array('1 Chronicles 19-20', '1 Peter 1'), 'secret' => array('Jonah 3', 'Luke 8') ),
      '25' => array( 'family' => array('1 Chronicles 21', '1 Peter 2'), 'secret' => array('Jonah 4', 'Luke 9') ),
      '26' => array( 'family' => array('1 Chronicles 22', '1 Peter 3'), 'secret' => array('Micah 1', 'Luke 10') ),
      '27' => array( 'family' => array('1 Chronicles 23', '1 Peter 4'), 'secret' => array('Micah 2', 'Luke 11') ),
      '28' => array( 'family' => array('1 Chronicles 24-25', '1 Peter 5'), 'secret' => array('Micah 3', 'Luke 12') ),
      '29' => array( 'family' => array('1 Chronicles 26-27', '2 Peter 1'), 'secret' => array('Micah 4', 'Luke 13') ),
      '30' => array( 'family' => array('1 Chronicles 28', '2 Peter 2'), 'secret' => array('Micah 5', 'Luke 14') ),
    ),
    '12' => array(
      '1' => array( 'family' => array('1 Chronicles 29', '2 Peter 3'), 'secret' => array('Micah 6', 'Luke 15') ),
      '2' => array( 'family' => array('2 Chronicles 1', '1 John 1'), 'secret' => array('Micah 7', 'Luke 16') ),
      '3' => array( 'family' => array('2 Chronicles 2', '1 John 2'), 'secret' => array('Nahum 1', 'Luke 17') ),
      '4' => array( 'family' => array('2 Chronicles 3-4', '1 John 3'), 'secret' => array('Nahum 2', 'Luke 18') ),
      '5' => array( 'family' => array('2 Chronicles 5:1-6:11', '1 John 4'), 'secret' => array('Nahum 3', 'Luke 19') ),
      '6' => array( 'family' => array('2 Chronicles 6:12-42', '1 John 5'), 'secret' => array('Habakkuk 1', 'Luke 20') ),
      '7' => array( 'family' => array('2 Chronicles 7', '2 John 1'), 'secret' => array('Habakkuk 2', 'Luke 21') ),
      '8' => array( 'family' => array('2 Chronicles 8', '3 John 1'), 'secret' => array('Habakkuk 3', 'Luke 22') ),
      '9' => array( 'family' => array('2 Chronicles 9', 'Jude 1'), 'secret' => array('Zephaniah 1', 'Luke 23') ),
      '10' => array( 'family' => array('2 Chronicles 10', 'Revelation 1'), 'secret' => array('Zephaniah 2', 'Luke 24') ),
      '11' => array( 'family' => array('2 Chronicles 11-12', 'Revelation 2'), 'secret' => array('Zephaniah 3', 'John 1') ),
      '12' => array( 'family' => array('2 Chronicles 13', 'Revelation 3'), 'secret' => array('Haggai 1', 'John 2') ),
      '13' => array( 'family' => array('2 Chronicles 14-15', 'Revelation 4'), 'secret' => array('Haggai 2', 'John 3') ),
      '14' => array( 'family' => array('2 Chronicles 16', 'Revelation 5'), 'secret' => array('Zechariah 1', 'John 4') ),
      '15' => array( 'family' => array('2 Chronicles 17', 'Revelation 6'), 'secret' => array('Zechariah 2', 'John 5') ),
      '16' => array( 'family' => array('2 Chronicles 18', 'Revelation 7'), 'secret' => array('Zechariah 3', 'John 6') ),
      '17' => array( 'family' => array('2 Chronicles 19-20', 'Revelation 8'), 'secret' => array('Zechariah 4', 'John 7') ),
      '18' => array( 'family' => array('2 Chronicles 21', 'Revelation 9'), 'secret' => array('Zechariah 5', 'John 8') ),
      '19' => array( 'family' => array('2 Chronicles 22-23', 'Revelation 10'), 'secret' => array('Zechariah 6', 'John 9') ),
      '20' => array( 'family' => array('2 Chronicles 24', 'Revelation 11'), 'secret' => array('Zechariah 7', 'John 10') ),
      '21' => array( 'family' => array('2 Chronicles 25', 'Revelation 12'), 'secret' => array('Zechariah 8', 'John 11') ),
      '22' => array( 'family' => array('2 Chronicles 26', 'Revelation 13'), 'secret' => array('Zechariah 9', 'John 12') ),
      '23' => array( 'family' => array('2 Chronicles 27-28', 'Revelation 14'), 'secret' => array('Zechariah 10', 'John 13') ),
      '24' => array( 'family' => array('2 Chronicles 29', 'Revelation 15'), 'secret' => array('Zechariah 11', 'John 14') ),
      '25' => array( 'family' => array('2 Chronicles 30', 'Revelation 16'), 'secret' => array('Zechariah 12:1-13:1', 'John 15') ),
      '26' => array( 'family' => array('2 Chronicles 31', 'Revelation 17'), 'secret' => array('Zechariah 13:2-9', 'John 16') ),
      '27' => array( 'family' => array('2 Chronicles 32', 'Revelation 18'), 'secret' => array('Zechariah 14', 'John 17') ),
      '28' => array( 'family' => array('2 Chronicles 33', 'Revelation 19'), 'secret' => array('Malachi 1', 'John 18') ),
      '29' => array( 'family' => array('2 Chronicles 34', 'Revelation 20'), 'secret' => array('Malachi 2', 'John 19') ),
      '30' => array( 'family' => array('2 Chronicles 35', 'Revelation 21'), 'secret' => array('Malachi 3', 'John 20') ),
      '31' => array( 'family' => array('2 Chronicles 36', 'Revelation 22'), 'secret' => array('Malachi 4', 'John 21') ),
    ),
  );
}

